-- SAMPLE CATALOGUE — NOT the real Dan Crackers / Gurusamy supplier data.
--
-- Transcribed from 'Selva Fancy Crackers — Diwali Price List 2026', the
-- representative sample catalogue the PRD names for data-model derivation
-- (PRD §3.6, §13). It is real, published pricing from an actual Sivakasi
-- seller — not fabricated — but it is NOT the Dan Crackers supplier's
-- catalogue. Used here only to seed a realistic local/dev/preview database
-- (17 categories, ~188 items, ₹24-3,750 range, matching PRD §3.6).
--
-- This file is only ever run by `supabase db reset` / local dev seeding.
-- It must NEVER be applied to the production project. Before launch, the
-- real catalogue must be imported via /admin/products/import (PRD §14.5).
--
-- A few prices are NULL where the source scan was illegible or ambiguous —
-- left blank rather than guessed, per the non-fabrication rule (PRD §14.3).

insert into categories (slug, name_en, name_ta, display_order) values
  ('sparklers', 'Sparklers', 'மத்தாப்பு', 1),
  ('ground-chakkars', 'Ground Chakkars', 'தரைச்சக்கரம்', 2),
  ('flower-pots', 'Flower Pots', 'பூச்சட்டி வகைகள்', 3),
  ('twinkling-star', 'Twinkling Star', 'சாட்டை', 4),
  ('bijili', 'Bijili', 'பிஜிலி', 5),
  ('sound-crackers', 'Sound Crackers', 'சவுண்டு பிஜிலி', 6),
  ('rocket', 'Rocket', 'ராக்கெட்', 7),
  ('bombs', 'Bombs', 'பாம்ஸ்', 8),
  ('elite-series', 'Elite Series', 'எலைட் சீரிஸ்', 9),
  ('colour-matches', 'Colour Matches', 'கலர் மத்தாப்பு', 10),
  ('ring-cap-serpent-eggs', 'Ring Cap & Serpent Eggs', 'ரிங் கேப் & சர்பண்ட் எக்', 11),
  ('chotaa-fancy', 'Chotaa Fancy', 'சோட்டா ஃபேன்சி', 12),
  ('sky-shots', 'Sky Shots', 'ஸ்கை ஷாட்ஸ்', 13),
  ('combo-aerial-shot', 'Combo Aerial Shot', 'காம்போ ஏரியல் ஷாட்', 14),
  ('multi-shot', 'Multi Shot', 'மல்டி ஷாட்', 15),
  ('new-version', 'New Version', 'புதிய மாடல் டிசைன்', 16),
  ('gift-box', 'Gift Box', 'கிப்ட் பாக்ஸ்', 17)
on conflict (slug) do nothing;

insert into products (sku, slug, name_en, name_ta, category_id, price, unit, is_discountable, image_url, status, is_bestseller, is_featured, display_order) values
  ('SFC-001', '7-cm-electric-sparklers', '7 cm Electric Sparklers', '7 செ.மீ. சாதா கம்பி', (select id from categories where slug = 'sparklers'), 30.00, 'pkt', true, NULL, 'active', false, false, 1),
  ('SFC-002', '7-cm-colour-sparklers', '7 cm Colour Sparklers', '7 செ.மீ. கலர் கம்பி', (select id from categories where slug = 'sparklers'), 32.00, 'pkt', true, NULL, 'active', false, false, 2),
  ('SFC-003', '7-cm-green-sparklers', '7 cm Green Sparklers', '7 செ.மீ. பச்சை கம்பி', (select id from categories where slug = 'sparklers'), 40.00, 'pkt', true, NULL, 'active', false, false, 3),
  ('SFC-004', '7-cm-red-sparklers', '7 cm Red Sparklers', '7 செ.மீ. சிவப்பு கம்பி', (select id from categories where slug = 'sparklers'), 42.00, 'pkt', true, NULL, 'active', false, false, 4),
  ('SFC-005', '10-cm-electric-sparklers', '10 cm Electric Sparklers', '10 செ.மீ. சாதா கம்பி', (select id from categories where slug = 'sparklers'), 48.00, 'pkt', true, NULL, 'active', false, false, 5),
  ('SFC-006', '10-cm-colour-sparklers', '10 cm Colour Sparklers', '10 செ.மீ. கலர் கம்பி', (select id from categories where slug = 'sparklers'), 54.00, 'pkt', true, NULL, 'active', false, false, 6),
  ('SFC-007', '10-cm-green-sparklers', '10 cm Green Sparklers', '10 செ.மீ. பச்சை கம்பி', (select id from categories where slug = 'sparklers'), 60.00, 'pkt', true, NULL, 'active', false, false, 7),
  ('SFC-008', '10-cm-red-sparklers', '10 cm Red Sparklers', '10 செ.மீ. சிவப்பு கம்பி', (select id from categories where slug = 'sparklers'), 66.00, 'pkt', true, NULL, 'active', false, false, 8),
  ('SFC-009', '15-cm-electric-sparklers', '15 cm Electric Sparklers', '15 செ.மீ. சாதா கம்பி', (select id from categories where slug = 'sparklers'), 126.00, 'pkt', true, NULL, 'active', false, false, 9),
  ('SFC-010', '15-cm-colour-sparklers', '15 cm Colour Sparklers', '15 செ.மீ. கலர் கம்பி', (select id from categories where slug = 'sparklers'), 140.00, 'pkt', true, NULL, 'active', false, false, 10),
  ('SFC-011', '15-cm-green-sparklers', '15 cm Green Sparklers', '15 செ.மீ. பச்சை கம்பி', (select id from categories where slug = 'sparklers'), 154.00, 'pkt', true, NULL, 'active', false, false, 11),
  ('SFC-012', '15-cm-red-sparklers', '15 cm Red Sparklers', '15 செ.மீ. சிவப்பு கம்பி', (select id from categories where slug = 'sparklers'), 168.00, 'pkt', true, NULL, 'active', false, false, 12),
  ('SFC-013', '30-cm-electric-sparklers', '30 cm Electric Sparklers', '30 செ.மீ. சாதா கம்பி', (select id from categories where slug = 'sparklers'), 130.00, 'pkt', true, NULL, 'active', false, false, 13),
  ('SFC-014', '30-cm-colour-sparklers', '30 cm Colour Sparklers', '30 செ.மீ. கலர் கம்பி', (select id from categories where slug = 'sparklers'), 144.00, 'pkt', true, NULL, 'active', false, false, 14),
  ('SFC-015', '30-cm-green-sparklers', '30 cm Green Sparklers', '30 செ.மீ. பச்சை கம்பி', (select id from categories where slug = 'sparklers'), 160.00, 'pkt', true, NULL, 'active', false, false, 15),
  ('SFC-016', '30-cm-red-sparklers', '30 cm Red Sparklers', '30 செ.மீ. சிவப்பு கம்பி', (select id from categories where slug = 'sparklers'), 172.00, 'pkt', true, NULL, 'active', false, false, 16),
  ('SFC-017', '50-cm-electric-sparklers', '50 cm Electric Sparklers', '50 செ.மீ. எலக்ட்ரிக்', (select id from categories where slug = 'sparklers'), 370.00, 'pkt', true, NULL, 'active', false, false, 17),
  ('SFC-018', '50-cm-green-sparklers', '50 cm Green Sparklers', '50 செ.மீ. பச்சை', (select id from categories where slug = 'sparklers'), 396.00, 'pkt', true, NULL, 'active', false, false, 18),
  ('SFC-019', '50-cm-colour-sparklers', '50 cm Colour Sparklers', '50 செ.மீ. கலர்', (select id from categories where slug = 'sparklers'), 396.00, 'pkt', true, NULL, 'active', false, false, 19),
  ('SFC-020', '10cm-miranda-orange-mercury-japan', '10cm Miranda Orange/Mercury/Japan', '10 செ.மீ. மிரான்டா ஆரஞ்சு / மெர்குரி / ஜப்பான்', (select id from categories where slug = 'sparklers'), 72.00, 'pkt', true, NULL, 'active', false, false, 20),
  ('SFC-021', '50-cm-electric-fancy', '50 cm Electric (Fancy)', '50 செ.மீ. எலக்ட்ரிக்', (select id from categories where slug = 'sparklers'), 420.00, 'pkt', true, NULL, 'active', false, false, 21),
  ('SFC-022', '50-cm-crackling', '50 cm Crackling', '50 செ.மீ. கிராக்லிங்', (select id from categories where slug = 'sparklers'), 504.00, 'pkt', true, NULL, 'active', false, false, 22),
  ('SFC-023', '50-cm-5-in-1-colour', '50 cm 5 in 1 Colour', '50 செ.மீ. 5 இன் 1 கலர்', (select id from categories where slug = 'sparklers'), 552.00, 'pkt', true, NULL, 'active', false, false, 23),
  ('SFC-024', '75-cm-electric', '75 cm Electric', '75 செ.மீ. எலக்ட்ரிக்', (select id from categories where slug = 'sparklers'), 660.00, 'pkt', true, NULL, 'active', false, false, 24),
  ('SFC-025', '75-cm-crackling', '75 cm Crackling', '75 செ.மீ. கிராக்லிங்', (select id from categories where slug = 'sparklers'), 744.00, 'pkt', true, NULL, 'active', false, false, 25),
  ('SFC-026', '75-cm-5-in-1-colour', '75 cm 5 in 1 Colour', '75 செ.மீ. 5 இன் 1 கலர்', (select id from categories where slug = 'sparklers'), 810.00, 'pkt', true, NULL, 'active', false, false, 26),
  ('SFC-027', 'dancing-rose-electric', 'Dancing Rose (Electric)', 'டான்சிங் ரோஸ் எலக்ட்ரிக்', (select id from categories where slug = 'sparklers'), 540.00, 'pkt', true, NULL, 'active', false, false, 27),
  ('SFC-028', 'dancing-rose-red-white', 'Dancing Rose (Red & White)', 'டான்சிங் ரோஸ் (சிவப்பு & வெள்ளை)', (select id from categories where slug = 'sparklers'), 540.00, 'pkt', true, NULL, 'active', false, false, 28),
  ('SFC-029', 'ground-chakkar-big', 'Ground Chakkar Big', 'தரைச்சக்கரம் பெரியது', (select id from categories where slug = 'ground-chakkars'), 96.00, 'pkt', true, NULL, 'active', false, false, 29),
  ('SFC-030', 'ground-chakkar-ashoka', 'Ground Chakkar Ashoka', 'தரைச்சக்கரம் அசோகா', (select id from categories where slug = 'ground-chakkars'), 144.00, 'pkt', true, NULL, 'active', false, false, 30),
  ('SFC-031', 'ground-chakkar-special', 'Ground Chakkar Special', 'தரைச்சக்கரம் ஸ்பெஷல்', (select id from categories where slug = 'ground-chakkars'), 180.00, 'pkt', true, NULL, 'active', false, false, 31),
  ('SFC-032', 'ground-chakkar-deluxe', 'Ground Chakkar Deluxe', 'தரைச்சக்கரம் டீலக்ஸ்', (select id from categories where slug = 'ground-chakkars'), 360.00, 'pkt', true, NULL, 'active', false, false, 32),
  ('SFC-033', 'ananda-s-ground-chakkar-special', 'Ananda''s Ground Chakkar Special', 'ஆனந்தாஸ் தரைச்சக்கரம் ஸ்பெஷல்', (select id from categories where slug = 'ground-chakkars'), 348.00, 'pkt', true, NULL, 'active', false, false, 33),
  ('SFC-034', 'ananda-s-classic-wheel', 'Ananda''s Classic Wheel', 'ஆனந்தாஸ் கிளாசிக் வீல்', (select id from categories where slug = 'ground-chakkars'), 264.00, 'pkt', true, NULL, 'active', false, false, 34),
  ('SFC-035', 'rottas-wheel-ayyan', 'Rottas Wheel - Ayyan', 'ரோட்டஸ் வீல் - அய்யன்', (select id from categories where slug = 'ground-chakkars'), 312.00, 'pkt', true, NULL, 'active', false, false, 35),
  ('SFC-036', 'whistling-wheel-ayyan', 'Whistling Wheel - Ayyan', 'விஸிலிங் வீல் - அய்யன்', (select id from categories where slug = 'ground-chakkars'), 540.00, 'pkt', true, NULL, 'active', false, false, 36),
  ('SFC-037', 'ananda-s-3-1-honda', 'Ananda''s 3-1 Honda', 'ஆனந்தாஸ் 3-1 ஹொண்டா', (select id from categories where slug = 'ground-chakkars'), 360.00, 'pkt', true, NULL, 'active', false, false, 37),
  ('SFC-038', 'ground-chakkar-special-green', 'Ground Chakkar Special Green', 'தரைச்சக்கரம் ஸ்பெஷல் பச்சை', (select id from categories where slug = 'ground-chakkars'), 630.00, 'pkt', true, NULL, 'active', false, false, 38),
  ('SFC-039', 'ananda-s-deluxe', 'Ananda''s Deluxe', 'ஆனந்தாஸ் டீலக்ஸ்', (select id from categories where slug = 'ground-chakkars'), 630.00, 'pkt', true, NULL, 'active', false, false, 39),
  ('SFC-040', 'ananda-s-roller-coaster', 'Ananda''s Roller Coaster', 'ஆனந்தாஸ் ரோலர் கோஸ்டர்', (select id from categories where slug = 'ground-chakkars'), 516.00, 'pkt', true, NULL, 'active', false, false, 40),
  ('SFC-041', 'silver-giant-wheel', 'Silver Giant Wheel', 'சில்வர் ஜெயின்ட் வீல்', (select id from categories where slug = 'ground-chakkars'), 480.00, 'pkt', true, NULL, 'active', false, false, 41),
  ('SFC-042', 'flower-pots-small', 'Flower Pots Small', 'பூச்சட்டி சிறியது', (select id from categories where slug = 'flower-pots'), 132.00, 'pkt', true, NULL, 'active', false, false, 42),
  ('SFC-043', 'flower-pots-big', 'Flower Pots Big', 'பூச்சட்டி பெரியது', (select id from categories where slug = 'flower-pots'), 180.00, 'pkt', true, NULL, 'active', false, false, 43),
  ('SFC-044', 'flower-pots-big-parasakthi', 'Flower Pots Big Parasakthi', 'பூச்சட்டி பெரியது பராசக்தி', (select id from categories where slug = 'flower-pots'), NULL, 'pkt', true, NULL, 'active', false, false, 44),
  ('SFC-045', 'flower-pots-special', 'Flower Pots Special', 'பூச்சட்டி ஸ்பெஷல்', (select id from categories where slug = 'flower-pots'), 240.00, 'pkt', true, NULL, 'active', false, false, 45),
  ('SFC-046', 'flower-pots-ashoka', 'Flower Pots Ashoka', 'பூச்சட்டி அசோகா', (select id from categories where slug = 'flower-pots'), 360.00, 'pkt', true, NULL, 'active', false, false, 46),
  ('SFC-047', 'f-p-dlx-5-pcs', 'F/P DLX (5 Pcs)', 'F/P டீலக்ஸ் (5 பீஸ்)', (select id from categories where slug = 'flower-pots'), 420.00, 'pkt', true, NULL, 'active', false, false, 47),
  ('SFC-048', 'colour-koti', 'Colour Koti', 'கலர் கோடி', (select id from categories where slug = 'flower-pots'), 600.00, 'pkt', true, NULL, 'active', false, false, 48),
  ('SFC-049', 'colour-changing', 'Colour Changing', 'கலர் சேஞ்சிங்', (select id from categories where slug = 'flower-pots'), 384.00, 'pkt', true, NULL, 'active', false, false, 49),
  ('SFC-050', 'crackling-tree', 'Crackling Tree', 'கிராக்லிங் ட்ரீ', (select id from categories where slug = 'flower-pots'), 552.00, 'pkt', true, NULL, 'active', false, false, 50),
  ('SFC-051', 'toys-fountain', 'Toys Fountain', 'டாய்ஸ் பவுண்டன்', (select id from categories where slug = 'flower-pots'), 234.00, 'pkt', true, NULL, 'active', false, false, 51),
  ('SFC-052', 'colour-koti-green-5-pcs', 'Colour Koti Green (5 Pcs)', 'கலர் கோடி பச்சை (5 பீஸ்)', (select id from categories where slug = 'flower-pots'), 1320.00, 'pkt', true, NULL, 'active', false, false, 52),
  ('SFC-053', 'colour-koti-10-pcs', 'Colour Koti (10 Pcs)', 'கலர் கோடி (10 பீஸ்)', (select id from categories where slug = 'flower-pots'), 540.00, 'pkt', true, NULL, 'active', false, false, 53),
  ('SFC-054', 'colour-koti-5-pcs-deluxe', 'Colour Koti (5 Pcs) Deluxe', 'கலர் கோடி (5 பீஸ்) டீலக்ஸ்', (select id from categories where slug = 'flower-pots'), 1080.00, 'pkt', true, NULL, 'active', false, false, 54),
  ('SFC-055', 'colour-koti-10-pcs-deluxe', 'Colour Koti (10 Pcs) Deluxe', 'கலர் கோடி (10 பீஸ்) டீலக்ஸ்', (select id from categories where slug = 'flower-pots'), 960.00, 'pkt', true, NULL, 'active', false, false, 55),
  ('SFC-056', 'skype-twitter', 'Skype / Twitter', 'ஸ்கைப் / ட்விட்டர்', (select id from categories where slug = 'flower-pots'), 360.00, 'pkt', true, NULL, 'active', false, false, 56),
  ('SFC-057', 'fantasy-peacock', 'Fantasy Peacock', 'பேன்டசி பீகாக்', (select id from categories where slug = 'flower-pots'), 360.00, 'pkt', true, NULL, 'active', false, false, 57),
  ('SFC-058', 'jolly-ranger', 'Jolly Ranger', 'ஜாலி ரேஞ்சர்', (select id from categories where slug = 'flower-pots'), 360.00, 'pkt', true, NULL, 'active', false, false, 58),
  ('SFC-059', 'lemon-tree-poppings', 'Lemon Tree - Poppings', 'லெமன் ட்ரீ பாப்பிங்ஸ்', (select id from categories where slug = 'flower-pots'), 480.00, 'pkt', true, NULL, 'active', false, false, 59),
  ('SFC-060', 'tri-colour-fountain', 'Tri Colour Fountain', 'ட்ரை கலர் பவுண்டன்', (select id from categories where slug = 'flower-pots'), 480.00, 'pkt', true, NULL, 'active', false, false, 60),
  ('SFC-061', 'selfie-stick-5-pcs-ananda-s', 'Selfie Stick (5 Pcs) Ananda''s', 'செல்ஃபி ஸ்டிக் (5 பீஸ்) ஆனந்தாஸ்', (select id from categories where slug = 'flower-pots'), 540.00, 'pkt', true, NULL, 'active', false, false, 61),
  ('SFC-062', 'selfie-stick-5-pcs', 'Selfie Stick (5 Pcs)', 'செல்ஃபி ஸ்டிக் (5 பீஸ்)', (select id from categories where slug = 'flower-pots'), 420.00, 'pkt', true, NULL, 'active', false, false, 62),
  ('SFC-063', '1-5-twinkling-star', '1.5" Twinkling Star', '1½ இன்ச் சாட்டை', (select id from categories where slug = 'twinkling-star'), 90.00, 'pkt', true, NULL, 'active', false, false, 63),
  ('SFC-064', '4-twinkling-star', '4" Twinkling Star', '4 இன்ச் சாட்டை', (select id from categories where slug = 'twinkling-star'), 180.00, 'pkt', true, NULL, 'active', false, false, 64),
  ('SFC-065', 'roman-candles', 'Roman Candles', 'ரோமன் கேண்டில்', (select id from categories where slug = 'twinkling-star'), 288.00, 'pkt', true, NULL, 'active', false, false, 65),
  ('SFC-066', 'bijili-50-pcs', 'Bijili (50 Pcs)', 'பிஜிலி (50 பீஸ்)', (select id from categories where slug = 'bijili'), 48.00, 'pkt', true, NULL, 'active', false, false, 66),
  ('SFC-067', 'red-bijili-100-pcs', 'Red Bijili (100 Pcs)', 'சிவப்பு பிஜிலி (100 பீஸ்)', (select id from categories where slug = 'bijili'), 72.00, 'pkt', true, NULL, 'active', false, false, 67),
  ('SFC-068', 'stripped-bijili-100-pcs', 'Stripped Bijili (100 Pcs)', 'ஸ்ட்ரைப்டு பிஜிலி (100 பீஸ்)', (select id from categories where slug = 'bijili'), 84.00, 'pkt', true, NULL, 'active', false, false, 68),
  ('SFC-069', '2-75-bird', '2.75" Bird', '2¾ இன்ச் பேர்டு', (select id from categories where slug = 'sound-crackers'), 24.00, 'pkt', true, NULL, 'active', false, false, 69),
  ('SFC-070', '3-5-lakshmi', '3.5" Lakshmi', '3½ இன்ச் லட்சுமி', (select id from categories where slug = 'sound-crackers'), 36.00, 'pkt', true, NULL, 'active', false, false, 70),
  ('SFC-071', '4-lakshmi', '4" Lakshmi', '4 இன்ச் லட்சுமி', (select id from categories where slug = 'sound-crackers'), 48.00, 'pkt', true, NULL, 'active', false, false, 71),
  ('SFC-072', '4-lakshmi-deluxe', '4" Lakshmi Deluxe', '4 இன்ச் லட்சுமி டீலக்ஸ்', (select id from categories where slug = 'sound-crackers'), 72.00, 'pkt', true, NULL, 'active', false, false, 72),
  ('SFC-073', '4-gold-lakshmi', '4" Gold Lakshmi', '4 இன்ச் கோல்டு லட்சுமி', (select id from categories where slug = 'sound-crackers'), 90.00, 'pkt', true, NULL, 'active', false, false, 73),
  ('SFC-074', 'hulk', 'Hulk', 'ஹல்க்', (select id from categories where slug = 'sound-crackers'), 90.00, 'pkt', true, NULL, 'active', false, false, 74),
  ('SFC-075', '2-sound', '2 Sound', '2 சவுண்டு', (select id from categories where slug = 'sound-crackers'), 72.00, 'pkt', true, NULL, 'active', false, false, 75),
  ('SFC-076', 'bahubali', 'Bahubali', 'பாகுபலி', (select id from categories where slug = 'sound-crackers'), 90.00, 'pkt', true, NULL, 'active', false, false, 76),
  ('SFC-077', 'joker-lion', 'Joker / Lion', 'ஜோக்கர் / லயன்', (select id from categories where slug = 'sound-crackers'), 120.00, 'pkt', true, NULL, 'active', false, false, 77),
  ('SFC-078', 'rocket-bomb', 'Rocket Bomb', 'ராக்கெட் பாம்', (select id from categories where slug = 'rocket'), 288.00, 'pkt', true, NULL, 'active', false, false, 78),
  ('SFC-079', 'whistling-rocket-5-pcs', 'Whistling Rocket (5 Pcs)', 'விசிலிங் ராக்கெட் (5 பீஸ்)', (select id from categories where slug = 'rocket'), 346.00, 'pkt', true, NULL, 'active', false, false, 79),
  ('SFC-080', 'whistling-rocket-10-pcs', 'Whistling Rocket (10 Pcs)', 'விசிலிங் ராக்கெட் (10 பீஸ்)', (select id from categories where slug = 'rocket'), 580.00, 'pkt', true, NULL, 'active', false, false, 80),
  ('SFC-081', 'fancy-peacock', 'Fancy Peacock', 'ஃபேன்சி பீகாக்', (select id from categories where slug = 'rocket'), 420.00, 'pkt', true, NULL, 'active', false, false, 81),
  ('SFC-082', 'tri-colour-fountain-small', 'Tri Colour Fountain Small', 'ட்ரை கலர் பவுண்டன் சிறியது', (select id from categories where slug = 'rocket'), 720.00, 'pkt', true, NULL, 'active', false, false, 82),
  ('SFC-083', 'bullet-bomb', 'Bullet Bomb', 'புல்லட் பாம்', (select id from categories where slug = 'bombs'), 72.00, 'pkt', true, NULL, 'active', false, false, 83),
  ('SFC-084', 'atom-bomb', 'Atom Bomb', 'ஆட்டம் பாம்', (select id from categories where slug = 'bombs'), 144.00, 'pkt', true, NULL, 'active', false, false, 84),
  ('SFC-085', 'hydro-bomb', 'Hydro Bomb', 'ஹைட்ரோ பாம்', (select id from categories where slug = 'bombs'), 174.00, 'pkt', true, NULL, 'active', false, false, 85),
  ('SFC-086', 'king-of-king', 'King of King', 'கிங் ஆப் கிங்', (select id from categories where slug = 'bombs'), 234.00, 'pkt', true, NULL, 'active', false, false, 86),
  ('SFC-087', 'marathon-bomb', 'Marathon Bomb', 'மாரத்தான் பாம்', (select id from categories where slug = 'bombs'), 288.00, 'pkt', true, NULL, 'active', false, false, 87),
  ('SFC-088', 'classic-bomb', 'Classic Bomb', 'கிளாசிக் பாம்', (select id from categories where slug = 'bombs'), 312.00, 'pkt', true, NULL, 'active', false, false, 88),
  ('SFC-089', 'agni', 'Agni', 'அக்னி பாம்', (select id from categories where slug = 'bombs'), 474.00, 'pkt', true, NULL, 'active', false, false, 89),
  ('SFC-090', '555-bomb', '555 Bomb', '555 பாம்', (select id from categories where slug = 'bombs'), 342.00, 'pkt', true, NULL, 'active', false, false, 90),
  ('SFC-091', 'digital-bomb', 'Digital Bomb', 'டிஜிட்டல் பாம்', (select id from categories where slug = 'bombs'), 576.00, 'pkt', true, NULL, 'active', false, false, 91),
  ('SFC-092', 'd-t-s-bomb', 'D T S Bomb', 'டி டி எஸ் பாம்', (select id from categories where slug = 'bombs'), 720.00, 'pkt', true, NULL, 'active', false, false, 92),
  ('SFC-093', 'assorted-cartoon-10-pcs', 'Assorted Cartoon (10 Pcs)', 'அசார்ட்டு கார்ட்டூன் (10 பீஸ்)', (select id from categories where slug = 'elite-series'), 72.00, 'pkt', true, NULL, 'active', false, false, 93),
  ('SFC-094', 'electric-stone-kit-kat', 'Electric Stone / Kit Kat', 'எலக்ட்ரிக் ஸ்டோன்', (select id from categories where slug = 'elite-series'), 116.00, 'pkt', true, NULL, 'active', false, false, 94),
  ('SFC-095', 'jee-boom-baa', 'Jee Boom Baa', 'ஜீ பூம் பா', (select id from categories where slug = 'elite-series'), 72.00, 'pkt', true, NULL, 'active', false, false, 95),
  ('SFC-096', 'photo-flash', 'Photo Flash', 'போட்டோ பிளாஷ்', (select id from categories where slug = 'elite-series'), 216.00, 'pkt', true, NULL, 'active', false, false, 96),
  ('SFC-097', 'selfie-stick-5-pcs-elite', 'Selfie Stick (5 Pcs) Elite', 'செல்பி ஸ்டிக் (5 பீஸ்)', (select id from categories where slug = 'elite-series'), 420.00, 'pkt', true, NULL, 'active', false, false, 97),
  ('SFC-098', 'child-money-bank-2-pcs', 'Child Money Bank (2 Pcs)', 'சைல்டு மணி பேங்க் (2 பீஸ்)', (select id from categories where slug = 'elite-series'), 390.00, 'pkt', true, NULL, 'active', false, false, 98),
  ('SFC-099', 'drone', 'Drone', 'ட்ரோன்', (select id from categories where slug = 'elite-series'), 400.00, 'pkt', true, NULL, 'active', false, false, 99),
  ('SFC-100', 'pambaram-10-pcs', 'Pambaram (10 Pcs)', 'பம்பரம் (10 பீஸ்)', (select id from categories where slug = 'elite-series'), 288.00, 'pkt', true, NULL, 'active', false, false, 100),
  ('SFC-101', 'helicoptar-5-pcs', 'Helicoptar (5 Pcs)', 'ஹெலிகாப்டர் (5 பீஸ்)', (select id from categories where slug = 'elite-series'), 252.00, 'pkt', true, NULL, 'active', false, false, 101),
  ('SFC-102', 'butterfly', 'Butterfly', 'பட்டர்பிளை', (select id from categories where slug = 'elite-series'), 252.00, 'pkt', true, NULL, 'active', false, false, 102),
  ('SFC-103', 'sky-shot', 'Sky Shot', 'ஸ்கை ஷாட்', (select id from categories where slug = 'elite-series'), 252.00, 'pkt', true, NULL, 'active', false, false, 103),
  ('SFC-104', 'killar-shot', 'Killar Shot', 'கில்லர் ஷாட்', (select id from categories where slug = 'elite-series'), 324.00, 'pkt', true, NULL, 'active', false, false, 104),
  ('SFC-105', 'colour-fountain-5-pcs', 'Colour Fountain (5 Pcs)', 'கலர் பவுண்டன் (5 பீஸ்)', (select id from categories where slug = 'elite-series'), 360.00, 'pkt', true, NULL, 'active', false, false, 105),
  ('SFC-106', 'thriller-siren-big-3-pcs', 'Thriller Siren Big (3 Pcs)', 'த்ரில்லர் சைரன் பிக் (3 பீஸ்)', (select id from categories where slug = 'elite-series'), 520.00, 'pkt', true, NULL, 'active', false, false, 106),
  ('SFC-107', 'siren-small-3-pcs', 'Siren Small (3 Pcs)', 'சைரன் ஸ்மால் (3 பீஸ்)', (select id from categories where slug = 'elite-series'), 332.00, 'pkt', true, NULL, 'active', false, false, 107),
  ('SFC-108', 'siren-big-2-pcs', 'Siren Big (2 Pcs)', 'சைரன் பிக் (2 பீஸ்)', (select id from categories where slug = 'elite-series'), 508.00, 'pkt', true, NULL, 'active', false, false, 108),
  ('SFC-109', 'tin-fountain', 'Tin Fountain', 'டின் பவுண்டன்', (select id from categories where slug = 'elite-series'), 288.00, 'pkt', true, NULL, 'active', false, false, 109),
  ('SFC-110', 'water-queen-falls', 'Water Queen Falls', 'வாட்டர் குயின் பால்ஸ்', (select id from categories where slug = 'elite-series'), 432.00, 'pkt', true, NULL, 'active', false, false, 110),
  ('SFC-111', 'colour-fog-5-pcs', 'Colour Fog (5 Pcs)', 'கலர் போக் (5 பீஸ்)', (select id from categories where slug = 'elite-series'), 520.00, 'pkt', true, NULL, 'active', false, false, 111),
  ('SFC-112', 'pada-peacock', 'Pada Peacock', 'படா பீகாக்', (select id from categories where slug = 'elite-series'), 1000.00, 'pkt', true, NULL, 'active', true, false, 112),
  ('SFC-113', 'master-cricket-pat', 'Master Cricket Pat', 'மாஸ்டர் கிரிக்கெட் பேட்', (select id from categories where slug = 'elite-series'), 426.00, 'pcs', true, NULL, 'active', false, false, 113),
  ('SFC-114', 'robin-max-cone', 'Robin Max Cone', 'ராபின் மேக்ஸ் கோன்', (select id from categories where slug = 'colour-matches'), 116.00, 'pkt', true, NULL, 'active', false, false, 114),
  ('SFC-115', 'super-king', 'Super King', 'சூப்பர் கிங்', (select id from categories where slug = 'colour-matches'), 200.00, 'pkt', true, NULL, 'active', false, false, 115),
  ('SFC-116', 'classic-5-in-1', 'Classic 5 in 1', 'கிளாசிக் 5 இன் 1', (select id from categories where slug = 'colour-matches'), 346.00, 'pkt', true, NULL, 'active', false, false, 116),
  ('SFC-117', '7-up-rainbow', '7 up Rainbow', '7 அப் ரெயின்போ', (select id from categories where slug = 'colour-matches'), 376.00, 'pkt', true, NULL, 'active', false, false, 117),
  ('SFC-118', 'vip-10-in-1-laptop', 'VIP 10 in 1 Laptop', 'விஐபி 10 இன் 1 லேப்டாப்', (select id from categories where slug = 'colour-matches'), 576.00, 'pkt', true, NULL, 'active', false, false, 118),
  ('SFC-119', 'roll-cap', 'Roll Cap', 'ரோல் கேப்', (select id from categories where slug = 'ring-cap-serpent-eggs'), 144.00, 'pkt', true, NULL, 'active', false, false, 119),
  ('SFC-120', 'black-serpent-big', 'Black Serpent Big', 'பிளாக் சர்பண்ட் பெரியது', (select id from categories where slug = 'ring-cap-serpent-eggs'), 144.00, 'pkt', true, NULL, 'active', false, false, 120),
  ('SFC-121', 'anaconda', 'Anaconda', 'அனகோண்டா', (select id from categories where slug = 'ring-cap-serpent-eggs'), 230.00, 'pkt', true, NULL, 'active', false, false, 121),
  ('SFC-122', 'epson', 'Epson', 'எப்சன்', (select id from categories where slug = 'chotaa-fancy'), 144.00, 'pkt', true, NULL, 'active', false, false, 122),
  ('SFC-123', 'fuji', 'Fuji', 'புஜி', (select id from categories where slug = 'chotaa-fancy'), 144.00, 'pkt', true, NULL, 'active', false, false, 123),
  ('SFC-124', 'kodak', 'Kodak', 'கோடாக்', (select id from categories where slug = 'chotaa-fancy'), 144.00, 'pkt', true, NULL, 'active', false, false, 124),
  ('SFC-125', 'canan', 'Canan', 'கெனான்', (select id from categories where slug = 'chotaa-fancy'), 144.00, 'pkt', true, NULL, 'active', false, false, 125),
  ('SFC-126', '2-sky-shooter-yellow-mg', '2 Sky Shooter Yellow MG', '2 ஸ்கை ஷூட்டர் மஞ்சள்', (select id from categories where slug = 'sky-shots'), 252.00, 'pkt', true, NULL, 'active', false, false, 126),
  ('SFC-127', '2-sky-shooter-orange-audi', '2 Sky Shooter Orange Audi', '2 ஸ்கை ஷூட்டர் ஆரஞ்சு', (select id from categories where slug = 'sky-shots'), 252.00, 'pkt', true, NULL, 'active', false, false, 127),
  ('SFC-128', '2-sky-shooter-red-swift', '2 Sky Shooter Red Swift', '2 ஸ்கை ஷூட்டர் சிவப்பு', (select id from categories where slug = 'sky-shots'), 252.00, 'pkt', true, NULL, 'active', false, false, 128),
  ('SFC-129', '2-sky-shooter-pink-jaguar', '2 Sky Shooter Pink Jaguar', '2 ஸ்கை ஷூட்டர் பிங்க்', (select id from categories where slug = 'sky-shots'), 252.00, 'pkt', true, NULL, 'active', false, false, 129),
  ('SFC-130', '2-sky-shooter-blue-land-rover', '2 Sky Shooter Blue Land Rover', '2 ஸ்கை ஷூட்டர் புளூ', (select id from categories where slug = 'sky-shots'), 252.00, 'pkt', true, NULL, 'active', false, false, 130),
  ('SFC-131', '3-5-rainbow-sky-eagle', '3.5" Rainbow Sky Eagle', '3½ இன்ச் ரெயின்போ ஸ்கை ஈகிள்', (select id from categories where slug = 'sky-shots'), 600.00, 'pkt', true, NULL, 'active', false, false, 131),
  ('SFC-132', '3-5-rainbow-sky-blood-shot', '3.5" Rainbow Sky Blood Shot', '3½ இன்ச் ரெயின்போ ஸ்கை பிளட் ஷாட்', (select id from categories where slug = 'sky-shots'), 600.00, 'pkt', true, NULL, 'active', false, false, 132),
  ('SFC-133', '3-5-rainbow-sky-stay-strong', '3.5" Rainbow Sky Stay Strong', '3½ இன்ச் ரெயின்போ ஸ்கை ஸ்டே ஸ்ட்ராங்', (select id from categories where slug = 'sky-shots'), 660.00, 'pkt', true, NULL, 'active', false, false, 133),
  ('SFC-134', '3-5-chori-double-ball', '3.5" Chori Double Ball', '3½ இன்ச் சோரி டபுள் பால்', (select id from categories where slug = 'sky-shots'), 960.00, 'pkt', true, NULL, 'active', false, false, 134),
  ('SFC-135', '4-mega-sky-racing', '4" Mega Sky Racing', '4 இன்ச் மேகா ஸ்கை ரேசிங்', (select id from categories where slug = 'sky-shots'), 780.00, 'pcs', true, NULL, 'active', false, false, 135),
  ('SFC-136', '4-mega-sky-hunter', '4" Mega Sky Hunter', '4 இன்ச் மேகா ஸ்கை ஹன்டர்', (select id from categories where slug = 'sky-shots'), 780.00, 'pcs', true, NULL, 'active', false, false, 136),
  ('SFC-137', '4-mega-sky-passion', '4" Mega Sky Passion', '4 இன்ச் மேகா ஸ்கை பேசியன்', (select id from categories where slug = 'sky-shots'), 780.00, 'pcs', true, NULL, 'active', false, false, 137),
  ('SFC-138', '4-mega-sky-volley-ball', '4" Mega Sky Volley Ball', '4 இன்ச் மேகா ஸ்கை வாலி பால்', (select id from categories where slug = 'sky-shots'), 780.00, 'pcs', true, NULL, 'active', false, false, 138),
  ('SFC-139', '4-mega-sky-nayakara', '4" Mega Sky Nayakara', '4 இன்ச் மேகா ஸ்கை நயாகரா', (select id from categories where slug = 'sky-shots'), 820.00, 'pcs', true, NULL, 'active', false, false, 139),
  ('SFC-140', '1-fanta-5-pcs', '1" Fanta (5 Pcs)', '1" ஃபேண்டா (5 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 420.00, 'pkt', true, NULL, 'active', false, false, 140),
  ('SFC-141', '1-dslr-5-pcs', '1" DSLR (5 Pcs)', '1" டி எஸ் எல் ஆர் (5 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 690.00, 'pkt', true, NULL, 'active', false, false, 141),
  ('SFC-142', '2-combo-3-pcs', '2" Combo (3 Pcs)', '2" காம்போ (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 600.00, 'pkt', true, NULL, 'active', false, false, 142),
  ('SFC-143', '2-combo-elite-3-pcs', '2" Combo Elite (3 Pcs)', '2" காம்போ எலைட் (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 720.00, 'pkt', true, NULL, 'active', false, false, 143),
  ('SFC-144', 'ananda-s-3-comets-1-pcs', 'Ananda''s 3" Comets (1 Pcs)', 'ஆனந்தா 3" காமெட்ஸ் (1 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1020.00, 'pkt', true, NULL, 'active', false, false, 144),
  ('SFC-145', 'ananda-s-3-double-ball-1-pcs', 'Ananda''s 3" Double Ball (1 Pcs)', 'ஆனந்தா 3" டபுள் பால் (1 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1200.00, 'pkt', true, NULL, 'active', false, false, 145),
  ('SFC-146', 'ananda-s-2-25-tangled-3-pcs', 'Ananda''s 2.25" Tangled (3 Pcs)', '2¼" டேங்கில்டு (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1440.00, 'pkt', true, NULL, 'active', false, false, 146),
  ('SFC-147', 'ananda-s-2-25-ice-age-3-pcs', 'Ananda''s 2.25" Ice Age (3 Pcs)', '2¼" ஐஸ் ஏஜ் (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1440.00, 'pkt', true, NULL, 'active', true, false, 147),
  ('SFC-148', 'ananda-s-2-75-cars-3-pcs', 'Ananda''s 2.75" Cars (3 Pcs)', '2¾" கார்ஸ் (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1560.00, 'pkt', true, NULL, 'active', false, false, 148),
  ('SFC-149', 'ananda-s-2-75-tarzen-3-pcs', 'Ananda''s 2.75" Tarzen (3 Pcs)', '2¾" டார்சன் (3 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1560.00, 'pkt', true, NULL, 'active', false, false, 149),
  ('SFC-150', '3-8-steps-captain-america-1-pcs', '3" 8 Steps Captain America (1 Pcs)', '3" 8 ஸ்டெப்ஸ் அமெரிக்கா (1 பீஸ்)', (select id from categories where slug = 'combo-aerial-shot'), 1020.00, 'pkt', true, NULL, 'active', false, false, 150),
  ('SFC-151', 'mighty-sword-ananda-s', 'Mighty Sword Ananda''s', 'மைட்டி ஸ்வார்டு ஆனந்தா', (select id from categories where slug = 'combo-aerial-shot'), 720.00, 'box', true, NULL, 'active', false, false, 151),
  ('SFC-152', 'dirates-gun-ananda-s', 'Dirates Gun Ananda''s', 'டைரட் கன் ஆனந்தா', (select id from categories where slug = 'combo-aerial-shot'), 600.00, 'box', true, NULL, 'active', false, false, 152),
  ('SFC-153', 'five-falls', 'Five Falls', 'ஃபைவ் பால்ஸ்', (select id from categories where slug = 'multi-shot'), 180.00, 'pkt', true, NULL, 'active', false, false, 153),
  ('SFC-154', '7-wonders', '7 Wonders', '7 வொண்டர்ஸ்', (select id from categories where slug = 'multi-shot'), 246.00, 'pkt', true, NULL, 'active', false, false, 154),
  ('SFC-155', 'space-warriors', 'Space Warriors', 'ஸ்பேஸ் வேரியர்ஸ்', (select id from categories where slug = 'multi-shot'), 288.00, 'pkt', true, NULL, 'active', false, false, 155),
  ('SFC-156', '7-shot', '7 Shot', '7 ஷாட்', (select id from categories where slug = 'multi-shot'), 348.00, 'pkt', true, NULL, 'active', true, false, 156),
  ('SFC-157', '12-shots', '12 Shots', '12 ஷாட்ஸ்', (select id from categories where slug = 'multi-shot'), 360.00, 'pkt', true, NULL, 'active', false, false, 157),
  ('SFC-158', 'kinder-pop', 'Kinder Pop', 'கிண்டர் பாப்', (select id from categories where slug = 'new-version'), 600.00, 'pkt', true, NULL, 'active', false, false, 158),
  ('SFC-159', 'star-pots', 'Star Pots', 'ஸ்டார் பாட்ஸ்', (select id from categories where slug = 'new-version'), 264.00, 'pkt', true, NULL, 'active', false, false, 159),
  ('SFC-160', 'golden-egg-2-pcs', 'Golden Egg (2 Pcs)', 'கோல்டன் எக் (2 பீஸ்)', (select id from categories where slug = 'new-version'), 390.00, 'pkt', true, NULL, 'active', false, false, 160),
  ('SFC-161', 'gun-spark-2-pcs', 'Gun Spark (2 Pcs)', 'கன் ஸ்பார்க் (2 பீஸ்)', (select id from categories where slug = 'new-version'), 390.00, 'pkt', true, NULL, 'active', false, false, 161),
  ('SFC-162', 'gadayutham', 'Gadayutham', 'கடாயுதம்', (select id from categories where slug = 'new-version'), 500.00, 'pcs', true, NULL, 'active', false, false, 162),
  ('SFC-163', 'feather-super', 'Feather Super', 'பெதர் சூப்பர்', (select id from categories where slug = 'new-version'), 260.00, 'pcs', true, NULL, 'active', false, false, 163),
  ('SFC-164', 'spl-guitar', 'Spl Guitar', 'ஸ்பெஷல் கிட்டார்', (select id from categories where slug = 'new-version'), 504.00, 'pcs', true, NULL, 'active', false, false, 164),
  ('SFC-165', 'guitar-music-band', 'Guitar Music Band', 'கிட்டார் மியூசிக் பாண்ட்', (select id from categories where slug = 'new-version'), 720.00, 'pcs', true, NULL, 'active', false, false, 165),
  ('SFC-166', 'red-sun-sun-feast-5-p-5w', 'Red Sun - Sun Feast (5 P-5W)', 'ரெட் சன் - சன் பீஸ்ட் (5 P-5W)', (select id from categories where slug = 'new-version'), 462.00, 'pcs', true, NULL, 'active', false, false, 166),
  ('SFC-167', 'hand-shot', 'Hand Shot', 'ஹேண்ட் ஷாட்', (select id from categories where slug = 'new-version'), 2940.00, 'pcs', true, NULL, 'active', true, false, 167),
  ('SFC-168', 'csk-bus-tricolour', 'CSK Bus Tricolour', 'CSK பஸ் ட்ரைகலர்', (select id from categories where slug = 'new-version'), 696.00, 'pcs', true, NULL, 'active', false, false, 168),
  ('SFC-169', '15-multi-colour-shot', '15 Multi Colour Shot', '15 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 275.00, 'pcs', false, NULL, 'active', false, false, 169),
  ('SFC-170', '25-raider-colour-shot', '25 Raider Colour Shot', '25 ரைடர் கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 350.00, 'pcs', false, NULL, 'active', false, false, 170),
  ('SFC-171', '30-multi-colour-shot', '30 Multi Colour Shot', '30 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), NULL, 'pcs', false, NULL, 'active', false, false, 171),
  ('SFC-172', '60-multi-colour-shot', '60 Multi Colour Shot', '60 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 900.00, 'pcs', false, NULL, 'active', false, false, 172),
  ('SFC-173', '100-multi-colour-shot', '100 Multi Colour Shot', '100 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 1600.00, 'pcs', false, NULL, 'active', false, false, 173),
  ('SFC-174', '120-multi-colour-shot', '120 Multi Colour Shot', '120 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 1800.00, 'pcs', false, NULL, 'active', false, false, 174),
  ('SFC-175', '10x10-ananda-s', '10x10 Ananda''s', '10x10 ஆனந்தாஸ்', (select id from categories where slug = 'multi-shot'), 3750.00, 'pcs', false, NULL, 'active', false, false, 175),
  ('SFC-176', '240-multi-colour-shot', '240 Multi Colour Shot', '240 மல்டி கலர் ஷாட்', (select id from categories where slug = 'multi-shot'), 3600.00, 'pcs', false, NULL, 'active', false, false, 176),
  ('SFC-177', 'ice-age-minions-gift-box-19-items', 'Ice Age Minions Gift Box (19 Items)', 'ஐஸ் ஏஜ் மினியன்ஸ் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 275.00, 'box', false, NULL, 'active', true, true, 177),
  ('SFC-178', 'dora-gift-box-19-items', 'Dora Gift Box (19 Items)', 'டோரா கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 300.00, 'box', false, NULL, 'active', true, false, 178),
  ('SFC-179', 'festival-gift-box-20-items', 'Festival Gift Box (20 Items)', 'பெஸ்டிவல் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 325.00, 'box', false, NULL, 'active', true, false, 179),
  ('SFC-180', 'mono-gift-box-21-items', 'Mono Gift Box (21 Items)', 'மோனோ கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 350.00, 'box', false, NULL, 'active', false, false, 180),
  ('SFC-181', 'angry-birds-gift-box-27-items', 'Angry Birds Gift Box (27 Items)', 'ஆங்கிரி பேர்ட்ஸ் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 450.00, 'box', false, NULL, 'active', true, false, 181),
  ('SFC-182', 'avenger-gift-box-28-items', 'Avenger Gift Box (28 Items)', 'அவெஞ்சர் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 475.00, 'box', false, NULL, 'active', false, false, 182),
  ('SFC-183', 'avatar-super-gift-box-30-items', 'Avatar Super Gift Box (30 Items)', 'அவதார் சூப்பர் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 550.00, 'box', false, NULL, 'active', false, false, 183),
  ('SFC-184', 'hulk-gift-box-36-items', 'Hulk Gift Box (36 Items)', 'ஹல்க் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 650.00, 'box', false, NULL, 'active', true, false, 184),
  ('SFC-185', 'angry-bird-gift-box-40-items', 'Angry Bird Gift Box (40 Items)', 'ஆங்கிரி பேர்டு கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 750.00, 'box', false, NULL, 'active', false, false, 185),
  ('SFC-186', 'paradise-gift-box-45-items', 'Paradise Gift Box (45 Items)', 'பாரடைஸ் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 850.00, 'box', false, NULL, 'active', false, false, 186),
  ('SFC-187', 'wonderful-gift-box-50-items', 'Wonderful Gift Box (50 Items)', 'வொண்டர்புல் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 1050.00, 'box', false, NULL, 'active', true, false, 187),
  ('SFC-188', 'carnival-gift-box-55-items', 'Carnival Gift Box (55 Items)', 'கார்னிவல் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 1250.00, 'box', false, NULL, 'active', false, false, 188),
  ('SFC-189', 'vip-champion-gift-box-60-items', 'VIP Champion Gift Box (60 Items)', 'விஐபி சேம்பியன் கிப்ட் பாக்ஸ்', (select id from categories where slug = 'gift-box'), 1500.00, 'box', false, NULL, 'active', true, true, 189)
on conflict (sku) do nothing;

-- Sample captains for local/dev testing of the referral system (§20).
-- Clearly fake — replace with real captains before launch.
insert into captains (code, token, name, phone, city, area, status) values
  ('RAJ12', 'raj12devtoken0001', 'TEST — Rajesh (dev)', '9000000001', 'Chennai', 'Perungudi', 'active'),
  ('PRI07', 'pri07devtoken0002', 'TEST — Priya (dev)', '9000000002', 'Chennai', 'Velachery', 'active')
on conflict (code) do nothing;

