-- Sree Sai Ram Crackers (= Kids Crackers Park) — 2026 retail price list seed.
-- Source: Retail Price list - 2026 Final.pdf, transcribed row-for-row (200 line items).
-- Archives the existing Selva Fancy Crackers catalogue (status -> 'archived', never deleted)
-- and replaces it with the 200 SSR-### products. Safe to re-run: upserts by sku.

-- ── Archive the outgoing Selva catalogue ────────────────────────────
update products set status = 'archived' where sku like 'SFC-%' and status <> 'archived';

-- ── New categories not already covered by the existing catalogue ───
insert into categories (slug, name_en, display_order) values
  ('kids-collections', 'Kids Collections', 100),
  ('fountain-fancy-novelties', 'Fountain & Fancy Novelties', 101),
  ('matches', 'Matches', 102),
  ('gun-and-caps', 'Gun & Caps', 103),
  ('thunder-crackers', 'Thunder Crackers', 104)
on conflict (slug) do nothing;

-- ── Sree Sai Ram products ────────────────────────────────────────────
insert into products (sku, slug, name_en, name_ta, category_id, mrp, unit, is_discountable, status, display_order)
values
  ('SSR-001', '2-75-kuruvi-1', '2.75 Kuruvi', null, (select id from categories where slug = 'sound-crackers'), 70.00, 'pkt', true, 'active', 1),
  ('SSR-002', '3-5-laxmi-2', '3.5 Laxmi', null, (select id from categories where slug = 'sound-crackers'), 130.00, 'pkt', true, 'active', 2),
  ('SSR-003', '4-deluxe-hulk-3', '4 Deluxe (Hulk)', null, (select id from categories where slug = 'sound-crackers'), 180.00, 'pkt', true, 'active', 3),
  ('SSR-004', '4-laxmi-dlx-4', '4" Laxmi (Dlx)', null, (select id from categories where slug = 'sound-crackers'), 310.00, 'pkt', true, 'active', 4),
  ('SSR-005', '4-super-mega-deluxe-5', '4" Super Mega Deluxe', null, (select id from categories where slug = 'sound-crackers'), 600.00, 'pkt', true, 'active', 5),
  ('SSR-006', 'gold-laxmi-6', 'Gold Laxmi', null, (select id from categories where slug = 'sound-crackers'), 300.00, 'pkt', true, 'active', 6),
  ('SSR-007', '4-5-bahubali-machine-7', '4.5" BahuBali (Machine)', null, (select id from categories where slug = 'sound-crackers'), 480.00, 'pkt', true, 'active', 7),
  ('SSR-008', '5-jallikattu-machine-8', '5" Jallikattu (Machine)', null, (select id from categories where slug = 'sound-crackers'), 620.00, 'pkt', true, 'active', 8),
  ('SSR-009', '6-lion-king-machine-9', '6" Lion King (Machine)', null, (select id from categories where slug = 'sound-crackers'), 800.00, 'pkt', true, 'active', 9),
  ('SSR-010', 'lion-gun-10', 'Lion Gun', null, (select id from categories where slug = 'sound-crackers'), 900.00, 'pkt', true, 'active', 10),
  ('SSR-011', 'old-is-gold-11', 'Old is Gold', null, (select id from categories where slug = 'sound-crackers'), 1800.00, 'pkt', true, 'active', 11),
  ('SSR-012', 'olai-vedi-20-pcs-12', 'Olai Vedi (20 Pcs)', null, (select id from categories where slug = 'sound-crackers'), 1560.00, 'pkt', true, 'active', 12),
  ('SSR-013', 'two-sound-13', 'Two Sound', null, (select id from categories where slug = 'sound-crackers'), 400.00, 'box', true, 'active', 13),
  ('SSR-014', 'ground-chakkar-big-14', 'Ground Chakkar Big', null, (select id from categories where slug = 'ground-chakkars'), 350.00, 'box', true, 'active', 14),
  ('SSR-015', 'ground-chakkar-special-15', 'Ground Chakkar Special', null, (select id from categories where slug = 'ground-chakkars'), 660.00, 'box', true, 'active', 15),
  ('SSR-016', 'ground-chakkar-deluxe-16', 'Ground Chakkar Deluxe', null, (select id from categories where slug = 'ground-chakkars'), 1240.00, 'box', true, 'active', 16),
  ('SSR-017', 'wire-chakkar-17', 'Wire Chakkar', null, (select id from categories where slug = 'ground-chakkars'), 1600.00, 'box', true, 'active', 17),
  ('SSR-018', 'whistling-chakkar-2-pcs-18', 'Whistling Chakkar (2 Pcs)', null, (select id from categories where slug = 'ground-chakkars'), 1400.00, 'box', true, 'active', 18),
  ('SSR-019', 'wizzling-dixier-5-pcs-19', 'Wizzling Dixier (5 Pcs)', null, (select id from categories where slug = 'ground-chakkars'), 1600.00, 'box', true, 'active', 19),
  ('SSR-020', 'candy-wheel-20', 'Candy Wheel', null, (select id from categories where slug = 'ground-chakkars'), 2000.00, 'box', true, 'active', 20),
  ('SSR-021', 'flower-pots-big-21', 'Flower Pots Big', null, (select id from categories where slug = 'flower-pots'), 750.00, 'box', true, 'active', 21),
  ('SSR-022', 'flower-pots-special-22', 'Flower Pots Special', null, (select id from categories where slug = 'flower-pots'), 900.00, 'box', true, 'active', 22),
  ('SSR-023', 'flower-pots-asoka-23', 'Flower Pots Asoka', null, (select id from categories where slug = 'flower-pots'), 1100.00, 'box', true, 'active', 23),
  ('SSR-024', 'gypsy-5-pcs-24', 'Gypsy (5 pcs)', null, (select id from categories where slug = 'flower-pots'), 1780.00, 'box', true, 'active', 24),
  ('SSR-025', 'flower-pots-deluxe-5-pcs-25', 'Flower Pots Deluxe (5 pcs)', null, (select id from categories where slug = 'flower-pots'), 1600.00, 'box', true, 'active', 25),
  ('SSR-026', 'flower-pots-super-deluxe-2-pcs-26', 'Flower Pots Super Deluxe (2 pcs)', null, (select id from categories where slug = 'flower-pots'), 1000.00, 'box', true, 'active', 26),
  ('SSR-027', 'colour-koti-27', 'Colour Koti', null, (select id from categories where slug = 'flower-pots'), 1800.00, 'box', true, 'active', 27),
  ('SSR-028', 'colour-koti-brand-dlx-28', 'Colour Koti Brand (Dlx)', null, (select id from categories where slug = 'flower-pots'), 3500.00, 'box', true, 'active', 28),
  ('SSR-029', 'colour-koti-brand-pot-girl-29', 'Colour Koti Brand (Pot Girl)', null, (select id from categories where slug = 'flower-pots'), 2000.00, 'box', true, 'active', 29),
  ('SSR-030', 'deluxe-tricolour-fountain-30', 'Deluxe Tricolour Fountain', null, (select id from categories where slug = 'flower-pots'), 2400.00, 'box', true, 'active', 30),
  ('SSR-031', 'jumbo-pots-31', 'Jumbo Pots', null, (select id from categories where slug = 'flower-pots'), 3500.00, 'box', true, 'active', 31),
  ('SSR-032', 'scooby-doo-fountain-5s-32', 'Scooby Doo Fountain 5''s', null, (select id from categories where slug = 'flower-pots'), null, 'box', true, 'unavailable', 32),
  ('SSR-033', '1-5ft-twinkling-star-33', '1.5ft Twinkling Star', null, (select id from categories where slug = 'twinkling-star'), 250.00, 'box', true, 'active', 33),
  ('SSR-034', '4ft-twinkling-star-34', '4ft Twinkling Star', null, (select id from categories where slug = 'twinkling-star'), 740.00, 'box', true, 'active', 34),
  ('SSR-035', 'jil-jil-1-5ft-twinkling-star-10-pkt-35', 'Jil Jil 1.5ft Twinkling Star (10 Pkt)', null, (select id from categories where slug = 'twinkling-star'), 1800.00, 'box', true, 'active', 35),
  ('SSR-036', 'colour-rocket-36', 'Colour Rocket', null, (select id from categories where slug = 'rocket'), 720.00, 'box', true, 'active', 36),
  ('SSR-037', 'musical-rocket-37', 'Musical Rocket', null, (select id from categories where slug = 'rocket'), 1320.00, 'box', true, 'active', 37),
  ('SSR-038', 'lunik-rocket-38', 'Lunik Rocket', null, (select id from categories where slug = 'rocket'), 1700.00, 'box', true, 'active', 38),
  ('SSR-039', '2-sound-rocket-39', '2 Sound Rocket', null, (select id from categories where slug = 'rocket'), 1800.00, 'box', true, 'active', 39),
  ('SSR-040', '3-sound-rocket-40', '3 Sound Rocket', null, (select id from categories where slug = 'rocket'), 1900.00, 'box', true, 'active', 40),
  ('SSR-041', 'atom-bomb-41', 'Atom Bomb', null, (select id from categories where slug = 'bombs'), null, 'box', true, 'unavailable', 41),
  ('SSR-042', 'hydro-bomb-42', 'Hydro Bomb', null, (select id from categories where slug = 'bombs'), 750.00, 'box', true, 'active', 42),
  ('SSR-043', 'king-bomb-43', 'King Bomb', null, (select id from categories where slug = 'bombs'), 1000.00, 'box', true, 'active', 43),
  ('SSR-044', 'classic-bomb-44', 'Classic Bomb', null, (select id from categories where slug = 'bombs'), 1200.00, 'box', true, 'active', 44),
  ('SSR-045', 'agni-bomb-45', 'Agni Bomb', null, (select id from categories where slug = 'bombs'), 2000.00, 'box', true, 'active', 45),
  ('SSR-046', 'digital-bomb-46', 'Digital Bomb', null, (select id from categories where slug = 'bombs'), 2650.00, 'pcs', true, 'active', 46),
  ('SSR-047', 'king-rider-bomb-47', 'King Rider Bomb', null, (select id from categories where slug = 'bombs'), 2900.00, 'pkt', true, 'active', 47),
  ('SSR-048', 'money-bank-2-pcs-48', 'Money Bank (2 Pcs)', null, (select id from categories where slug = 'bombs'), 2100.00, 'pkt', true, 'active', 48),
  ('SSR-049', '100-bijili-49', '100 Bijili', null, (select id from categories where slug = 'bijili'), 400.00, 'box', true, 'active', 49),
  ('SSR-050', 'stipped-bijili-100-pcs-50', 'Stipped Bijili (100 Pcs)', null, (select id from categories where slug = 'bijili'), 500.00, 'box', true, 'active', 50),
  ('SSR-051', 'kit-kat-51', 'Kit Kat', null, (select id from categories where slug = 'kids-collections'), 260.00, 'box', true, 'active', 51),
  ('SSR-052', 'photo-flash-5-pcs-52', 'Photo Flash (5 pcs)', null, (select id from categories where slug = 'kids-collections'), 460.00, 'box', true, 'active', 52),
  ('SSR-053', 'tirisullam-53', 'Tirisullam', null, (select id from categories where slug = 'kids-collections'), 2200.00, 'box', true, 'active', 53),
  ('SSR-054', 'bat-and-ball-54', 'Bat and Ball', null, (select id from categories where slug = 'kids-collections'), 2000.00, 'pcs', true, 'active', 54),
  ('SSR-055', 'fire-egg-2-pcs-55', 'Fire Egg (2 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1800.00, 'box', true, 'active', 55),
  ('SSR-056', 'gold-stick-2-pcs-56', 'Gold Stick (2 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1290.00, 'box', true, 'active', 56),
  ('SSR-057', 'damo-sea-horse-shark-57', 'Damo Sea Horse, Shark', null, (select id from categories where slug = 'kids-collections'), 1190.00, 'box', true, 'active', 57),
  ('SSR-058', 'selfie-stick-3-pcs-58', 'Selfie Stick (3 pcs)', null, (select id from categories where slug = 'kids-collections'), 500.00, 'box', true, 'active', 58),
  ('SSR-059', 'ultra-pencil-3-pcs-59', 'Ultra Pencil (3 pcs)', null, (select id from categories where slug = 'kids-collections'), 790.00, 'box', true, 'active', 59),
  ('SSR-060', 'dora-singer-5-pcs-60', 'Dora Singer (5 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1590.00, 'box', true, 'active', 60),
  ('SSR-061', 'butterfly-61', 'Butterfly', null, (select id from categories where slug = 'kids-collections'), 800.00, 'box', true, 'active', 61),
  ('SSR-062', 'up-5-pcs-62', 'UP (5 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1460.00, 'box', true, 'active', 62),
  ('SSR-063', 'colour-fountain-mini-63', 'Colour Fountain Mini', null, (select id from categories where slug = 'kids-collections'), 1820.00, 'box', true, 'active', 63),
  ('SSR-064', 'mottu-pattlu-2pcs-64', 'Mottu Pattlu (2Pcs)', null, (select id from categories where slug = 'kids-collections'), 2500.00, 'box', true, 'active', 64),
  ('SSR-065', 'wounderla-65', 'Wounderla', null, (select id from categories where slug = 'kids-collections'), 3000.00, 'box', true, 'active', 65),
  ('SSR-066', 'robo-kids-minion-5-pcs-66', 'Robo Kids / Minion (5 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1800.00, 'box', true, 'active', 66),
  ('SSR-067', 'kungfu-panda-5-pcs-67', 'Kungfu panda (5 Pcs)', null, (select id from categories where slug = 'kids-collections'), 3000.00, 'box', true, 'active', 67),
  ('SSR-068', 'i-cone-2-pcs-68', 'I Cone (2 Pcs)', null, (select id from categories where slug = 'kids-collections'), 2300.00, 'box', true, 'active', 68),
  ('SSR-069', 'toy-fountain-69', 'Toy Fountain', null, (select id from categories where slug = 'kids-collections'), 2600.00, 'box', true, 'active', 69),
  ('SSR-070', 'top-gun-2-pcs-70', 'Top Gun (2 Pcs)', null, (select id from categories where slug = 'kids-collections'), 1000.00, 'box', true, 'active', 70),
  ('SSR-071', 'lollipop-71', 'Lollipop', null, (select id from categories where slug = 'kids-collections'), 1800.00, 'box', true, 'active', 71),
  ('SSR-072', 'sun-light-72', 'Sun Light', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1000.00, 'box', true, 'active', 72),
  ('SSR-073', 'moon-light-73', 'Moon Light', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1000.00, 'box', true, 'active', 73),
  ('SSR-074', '900-cc-74', '900 CC', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1500.00, 'box', true, 'active', 74),
  ('SSR-075', 'bambaram-75', 'Bambaram', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1100.00, 'box', true, 'active', 75),
  ('SSR-076', 'helicopter-76', 'Helicopter', null, (select id from categories where slug = 'fountain-fancy-novelties'), 900.00, 'box', true, 'active', 76),
  ('SSR-077', 'drone-77', 'Drone', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1100.00, 'box', true, 'active', 77),
  ('SSR-078', 'disco-shower-78', 'Disco Shower', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1000.00, 'box', true, 'active', 78),
  ('SSR-079', 'mini-peacock-79', 'Mini Peacock', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1100.00, 'box', true, 'active', 79),
  ('SSR-080', 'dancing-peacock-80', 'Dancing Peacock', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1400.00, 'box', true, 'active', 80),
  ('SSR-081', 'magic-peacock-81', 'Magic Peacock', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1800.00, 'box', true, 'active', 81),
  ('SSR-082', 'bada-peacock-82', 'Bada Peacock', null, (select id from categories where slug = 'fountain-fancy-novelties'), 3500.00, 'pcs', true, 'active', 82),
  ('SSR-083', '4-4-wheel-5-pcs-83', '4*4 Wheel (5 Pcs)', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1600.00, 'box', true, 'active', 83),
  ('SSR-084', 'shin-chan-5-pcs-84', 'Shin Chan (5 Pcs)', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1150.00, 'box', true, 'active', 84),
  ('SSR-085', '90-watts-85', '90 Watts', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1350.00, 'pcs', true, 'active', 85),
  ('SSR-086', 'tin-beer-86', 'Tin Beer', null, (select id from categories where slug = 'fountain-fancy-novelties'), 750.00, 'box', true, 'active', 86),
  ('SSR-087', 'siren-5-pcs-87', 'Siren (5 Pcs)', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1400.00, 'box', true, 'active', 87),
  ('SSR-088', 'mega-siren-3-pcs-88', 'Mega Siren (3 Pcs)', null, (select id from categories where slug = 'fountain-fancy-novelties'), 2000.00, 'box', true, 'active', 88),
  ('SSR-089', 'colour-smoke-89', 'Colour Smoke', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1300.00, 'box', true, 'active', 89),
  ('SSR-090', 'pom-pom-90', 'Pom Pom', null, (select id from categories where slug = 'fountain-fancy-novelties'), 2000.00, 'box', true, 'active', 90),
  ('SSR-091', 'operation-sindoor-9-in-1-91', 'Operation Sindoor 9 in 1', null, (select id from categories where slug = 'fountain-fancy-novelties'), 4800.00, 'box', true, 'active', 91),
  ('SSR-092', '4-water-falls-fountain-92', '4" Water Falls Fountain', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1500.00, 'pcs', true, 'active', 92),
  ('SSR-093', '4-pop-corn-fountain-93', '4" Pop Corn Fountain', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1500.00, 'pcs', true, 'active', 93),
  ('SSR-094', '4-water-falls-fountain-dlx-94', '4" Water Falls Fountain (Dlx)', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1500.00, 'pcs', true, 'active', 94),
  ('SSR-095', '6-lets-party-fountain-95', '6" Let''s Party Fountain', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1900.00, 'pcs', true, 'active', 95),
  ('SSR-096', 'cylinder-bomb-96', 'Cylinder Bomb', null, (select id from categories where slug = 'fountain-fancy-novelties'), 2000.00, 'pcs', true, 'active', 96),
  ('SSR-097', 'dragon-warrior-97', 'Dragon Warrior', null, (select id from categories where slug = 'fountain-fancy-novelties'), 700.00, 'pcs', true, 'active', 97),
  ('SSR-098', 'zodic-spinner-5-pcs-98', 'Zodic Spinner 5 Pcs', null, (select id from categories where slug = 'fountain-fancy-novelties'), 2600.00, 'box', true, 'active', 98),
  ('SSR-099', 'ninijan-chakkar-2-pcs-99', 'Ninijan Chakkar 2 Pcs', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1800.00, 'box', true, 'active', 99),
  ('SSR-100', 'lemon-tree-100', 'Lemon Tree', null, (select id from categories where slug = 'fountain-fancy-novelties'), 1700.00, 'pcs', true, 'active', 100),
  ('SSR-101', 'little-dove-101', 'Little Dove', null, (select id from categories where slug = 'fountain-fancy-novelties'), 900.00, 'pcs', true, 'active', 101),
  ('SSR-102', 'cocktail-spinner-10-pcs-102', 'Cocktail Spinner 10 Pcs', null, (select id from categories where slug = 'fountain-fancy-novelties'), 900.00, 'box', true, 'active', 102),
  ('SSR-103', '7-shot-classic-103', '7 shot Classic', null, (select id from categories where slug = 'multi-shot'), 1100.00, 'box', true, 'active', 103),
  ('SSR-104', '12-shot-multi-clr-with-rider-104', '12 Shot Multi clr with Rider', null, (select id from categories where slug = 'multi-shot'), 1700.00, 'pcs', true, 'active', 104),
  ('SSR-105', '12-shot-classic-105', '12 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 2100.00, 'pcs', true, 'active', 105),
  ('SSR-106', '15-colour-smoke-shot-106', '15 Colour Smoke Shot', null, (select id from categories where slug = 'multi-shot'), 3200.00, 'pcs', true, 'active', 106),
  ('SSR-107', 'seeti-maar-whistling-rider-107', 'Seeti Maar Whistling Rider', null, (select id from categories where slug = 'multi-shot'), 1700.00, 'pcs', true, 'active', 107),
  ('SSR-108', '25-shot-rider-108', '25 Shot Rider', null, (select id from categories where slug = 'multi-shot'), 2400.00, 'pcs', true, 'active', 108),
  ('SSR-109', '25-shot-classic-109', '25 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 3200.00, 'pcs', true, 'active', 109),
  ('SSR-110', '30-shot-classic-110', '30 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 3500.00, 'pcs', true, 'active', 110),
  ('SSR-111', '30-shot-permium-111', '30 Shot Permium', null, (select id from categories where slug = 'multi-shot'), 3750.00, 'pcs', true, 'active', 111),
  ('SSR-112', '60-shot-classic-112', '60 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 7000.00, 'pcs', true, 'active', 112),
  ('SSR-113', '60-shot-permium-113', '60 Shot Permium', null, (select id from categories where slug = 'multi-shot'), 7500.00, 'pcs', true, 'active', 113),
  ('SSR-114', '60-shot-s-k-maruthi-114', '60 Shot (S.K, Maruthi)', null, (select id from categories where slug = 'multi-shot'), 9000.00, 'pcs', true, 'active', 114),
  ('SSR-115', '120-shot-classic-115', '120 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 14000.00, 'pcs', true, 'active', 115),
  ('SSR-116', '120-shot-permium-116', '120 Shot Permium', null, (select id from categories where slug = 'multi-shot'), 15000.00, 'pcs', true, 'active', 116),
  ('SSR-117', '120-shot-s-k-117', '120 Shot S.K', null, (select id from categories where slug = 'multi-shot'), 18000.00, 'pcs', true, 'active', 117),
  ('SSR-118', '240-shot-classic-118', '240 Shot Classic', null, (select id from categories where slug = 'multi-shot'), 28000.00, 'pcs', true, 'active', 118),
  ('SSR-119', '240-shot-permium-119', '240 Shot Permium', null, (select id from categories where slug = 'multi-shot'), 30000.00, 'pcs', true, 'active', 119),
  ('SSR-120', 'paris-party-5-4-120', 'Paris Party 5*4', null, (select id from categories where slug = 'multi-shot'), 11000.00, 'pcs', true, 'active', 120),
  ('SSR-121', 'whistling-25-shot-121', 'Whistling 25 Shot', null, (select id from categories where slug = 'multi-shot'), 11000.00, 'pcs', true, 'active', 121),
  ('SSR-122', 'mr-beean-5-pcs-122', 'Mr.Beean (5 Pcs)', null, (select id from categories where slug = 'sky-shots'), 1000.00, 'box', true, 'active', 122),
  ('SSR-123', 'alladin-2-pcs-123', 'Alladin (2 Pcs)', null, (select id from categories where slug = 'sky-shots'), 600.00, 'box', true, 'active', 123),
  ('SSR-124', 'chotta-pipe-124', 'Chotta Pipe', null, (select id from categories where slug = 'sky-shots'), 380.00, 'pcs', true, 'active', 124),
  ('SSR-125', 'super-star-double-ball-125', 'Super Star (Double Ball)', null, (select id from categories where slug = 'sky-shots'), 900.00, 'pcs', true, 'active', 125),
  ('SSR-126', '1-75-pipe-3pcs-126', '1.75 Pipe (3pcs)', null, (select id from categories where slug = 'sky-shots'), 2500.00, 'pcs', true, 'active', 126),
  ('SSR-127', '2-pipe-127', '2" Pipe', null, (select id from categories where slug = 'sky-shots'), 900.00, 'box', true, 'active', 127),
  ('SSR-128', '2-pipe-classic-128', '2" Pipe Classic', null, (select id from categories where slug = 'sky-shots'), 1390.00, 'box', true, 'active', 128),
  ('SSR-129', '2-pipe-3-pcs-129', '2" Pipe (3 Pcs)', null, (select id from categories where slug = 'sky-shots'), null, 'box', true, 'unavailable', 129),
  ('SSR-130', '3-5-pipe-130', '3.5" Pipe', null, (select id from categories where slug = 'sky-shots'), 2800.00, 'pcs', true, 'active', 130),
  ('SSR-131', '3-5-nayagara-131', '3.5" nayagara', null, (select id from categories where slug = 'sky-shots'), 3000.00, 'pcs', true, 'active', 131),
  ('SSR-132', '4-pipe-single-132', '4" Pipe (Single)', null, (select id from categories where slug = 'sky-shots'), 3500.00, 'pcs', true, 'active', 132),
  ('SSR-133', '4-pipe-double-ball-133', '4" Pipe Double Ball', null, (select id from categories where slug = 'sky-shots'), 5500.00, 'pcs', true, 'active', 133),
  ('SSR-134', '5-pipe-2-pcs-134', '5" Pipe (2 Pcs)', null, (select id from categories where slug = 'sky-shots'), 9490.00, 'pcs', true, 'active', 134),
  ('SSR-135', 'big-pop-coral-pipe-135', 'Big Pop & Coral Pipe', null, (select id from categories where slug = 'sky-shots'), 3200.00, 'pcs', true, 'active', 135),
  ('SSR-136', '3-step-3-pcs-136', '3 Step (3 Pcs)', null, (select id from categories where slug = 'sky-shots'), 3600.00, 'pcs', true, 'active', 136),
  ('SSR-137', '7-step-137', '7 Step', null, (select id from categories where slug = 'sky-shots'), 3900.00, 'pcs', true, 'active', 137),
  ('SSR-138', '12-step-138', '12 Step', null, (select id from categories where slug = 'sky-shots'), 4600.00, 'pcs', true, 'active', 138),
  ('SSR-139', '6-pipe-2-pcs-139', '6" Pipe (2 Pcs)', null, (select id from categories where slug = 'sky-shots'), 11990.00, 'pcs', true, 'active', 139),
  ('SSR-140', 'tesla-140', 'Tesla', null, (select id from categories where slug = 'sky-shots'), 5500.00, 'pcs', true, 'active', 140),
  ('SSR-141', 'love-dose-141', 'Love Dose', null, (select id from categories where slug = 'sky-shots'), 1600.00, 'pcs', true, 'active', 141),
  ('SSR-142', '10cm-electric-142', '10cm Electric', null, (select id from categories where slug = 'sparklers'), 180.00, 'box', true, 'active', 142),
  ('SSR-143', '10cm-colour-143', '10cm Colour', null, (select id from categories where slug = 'sparklers'), 200.00, 'box', true, 'active', 143),
  ('SSR-144', '10cm-green-144', '10cm Green', null, (select id from categories where slug = 'sparklers'), 220.00, 'box', true, 'active', 144),
  ('SSR-145', '10cm-red-145', '10cm Red', null, (select id from categories where slug = 'sparklers'), 260.00, 'box', true, 'active', 145),
  ('SSR-146', '10cm-silver-drops-146', '10cm Silver Drops', null, (select id from categories where slug = 'sparklers'), 300.00, 'box', true, 'active', 146),
  ('SSR-147', '12cm-electric-147', '12cm Electric', null, (select id from categories where slug = 'sparklers'), 250.00, 'box', true, 'active', 147),
  ('SSR-148', '12cm-colour-148', '12cm Colour', null, (select id from categories where slug = 'sparklers'), 280.00, 'box', true, 'active', 148),
  ('SSR-149', '12cm-green-149', '12cm Green', null, (select id from categories where slug = 'sparklers'), 310.00, 'box', true, 'active', 149),
  ('SSR-150', '12cm-red-150', '12cm Red', null, (select id from categories where slug = 'sparklers'), 350.00, 'box', true, 'active', 150),
  ('SSR-151', '15cm-electric-151', '15cm Electric', null, (select id from categories where slug = 'sparklers'), 380.00, 'box', true, 'active', 151),
  ('SSR-152', '15cm-colour-152', '15cm Colour', null, (select id from categories where slug = 'sparklers'), 420.00, 'box', true, 'active', 152),
  ('SSR-153', '15cm-green-153', '15cm Green', null, (select id from categories where slug = 'sparklers'), 460.00, 'box', true, 'active', 153),
  ('SSR-154', '15cm-red-154', '15cm Red', null, (select id from categories where slug = 'sparklers'), 520.00, 'box', true, 'active', 154),
  ('SSR-155', '15cm-silver-drops-155', '15cm Silver Drops', null, (select id from categories where slug = 'sparklers'), 700.00, 'box', true, 'active', 155),
  ('SSR-156', '15cm-5-in-1-156', '15cm 5 in 1', null, (select id from categories where slug = 'sparklers'), 3000.00, 'box', true, 'active', 156),
  ('SSR-157', '30cm-electric-157', '30cm Electric', null, (select id from categories where slug = 'sparklers'), 380.00, 'box', true, 'active', 157),
  ('SSR-158', '30cm-colour-158', '30cm Colour', null, (select id from categories where slug = 'sparklers'), 420.00, 'box', true, 'active', 158),
  ('SSR-159', '30cm-green-159', '30cm Green', null, (select id from categories where slug = 'sparklers'), 460.00, 'box', true, 'active', 159),
  ('SSR-160', '30cm-red-160', '30cm Red', null, (select id from categories where slug = 'sparklers'), 520.00, 'box', true, 'active', 160),
  ('SSR-161', '50cm-electric-161', '50cm Electric', null, (select id from categories where slug = 'sparklers'), 1700.00, 'box', true, 'active', 161),
  ('SSR-162', '50cm-colour-162', '50cm Colour', null, (select id from categories where slug = 'sparklers'), 1900.00, 'box', true, 'active', 162),
  ('SSR-163', '50cm-multi-mix-163', '50cm Multi Mix', null, (select id from categories where slug = 'sparklers'), 1950.00, 'box', true, 'active', 163),
  ('SSR-164', 'smoky-stick-164', 'Smoky Stick', null, (select id from categories where slug = 'sparklers'), 650.00, 'box', true, 'active', 164),
  ('SSR-165', 'rotating-sparklers-165', 'Rotating Sparklers', null, (select id from categories where slug = 'sparklers'), 2500.00, 'box', true, 'active', 165),
  ('SSR-166', 'heartin-sparklers-166', 'Heartin Sparklers', null, (select id from categories where slug = 'sparklers'), 700.00, 'box', true, 'active', 166),
  ('SSR-167', 'super-kings-matchs-167', 'Super Kings Matchs', null, (select id from categories where slug = 'matches'), 82.00, 'box', false, 'active', 167),
  ('SSR-168', 'classic-matches-5-in-1-168', 'Classic Matches 5 in 1', null, (select id from categories where slug = 'matches'), 150.00, 'box', false, 'active', 168),
  ('SSR-169', 'top-10-matches-169', 'Top 10 Matches', null, (select id from categories where slug = 'matches'), 240.00, 'box', false, 'active', 169),
  ('SSR-170', 'gun-special-170', 'GUN - SPECIAL', null, (select id from categories where slug = 'gun-and-caps'), 100.00, 'pcs', false, 'active', 170),
  ('SSR-171', 'gun-premium-171', 'GUN - PREMIUM', null, (select id from categories where slug = 'gun-and-caps'), 150.00, 'pcs', false, 'active', 171),
  ('SSR-172', 'gun-ak-45-172', 'GUN - AK 45', null, (select id from categories where slug = 'gun-and-caps'), 280.00, 'pcs', false, 'active', 172),
  ('SSR-173', 'ring-cap-173', 'RING CAP', null, (select id from categories where slug = 'gun-and-caps'), 16.00, 'pcs', false, 'active', 173),
  ('SSR-174', 'sky-lander-174', 'Sky Lander', null, (select id from categories where slug = 'gun-and-caps'), 30.00, 'pcs', false, 'active', 174),
  ('SSR-175', 'master-piece-10-10-m-c-175', 'Master Piece 10*10 M/C', null, (select id from categories where slug = 'thunder-crackers'), 3200.00, 'box', false, 'active', 175),
  ('SSR-176', '28-chorsa-176', '28 Chorsa', null, (select id from categories where slug = 'thunder-crackers'), 17.00, 'pkt', false, 'active', 176),
  ('SSR-177', '28-gaint-177', '28 Gaint', null, (select id from categories where slug = 'thunder-crackers'), 25.00, 'pkt', false, 'active', 177),
  ('SSR-178', '56-gaint-178', '56 Gaint', null, (select id from categories where slug = 'thunder-crackers'), 50.00, 'pkt', false, 'active', 178),
  ('SSR-179', '24-deluxe-179', '24 Deluxe', null, (select id from categories where slug = 'thunder-crackers'), 45.00, 'pkt', false, 'active', 179),
  ('SSR-180', '50-deluxe-180', '50 Deluxe', null, (select id from categories where slug = 'thunder-crackers'), 110.00, 'pkt', false, 'active', 180),
  ('SSR-181', '100-deluxe-181', '100 Deluxe', null, (select id from categories where slug = 'thunder-crackers'), 220.00, 'pkt', false, 'active', 181),
  ('SSR-182', '100-wala-182', '100 Wala', null, (select id from categories where slug = 'thunder-crackers'), 35.00, 'pkt', false, 'active', 182),
  ('SSR-183', '1k-sh-183', '1K Sh', null, (select id from categories where slug = 'thunder-crackers'), 150.00, 'pcs', false, 'active', 183),
  ('SSR-184', '2k-sh-184', '2K Sh', null, (select id from categories where slug = 'thunder-crackers'), 300.00, 'pcs', false, 'active', 184),
  ('SSR-185', '5k-sh-185', '5K Sh', null, (select id from categories where slug = 'thunder-crackers'), 750.00, 'pcs', false, 'active', 185),
  ('SSR-186', '10k-sh-186', '10K Sh', null, (select id from categories where slug = 'thunder-crackers'), 1500.00, 'pcs', false, 'active', 186),
  ('SSR-187', '1k-f-187', '1K F', null, (select id from categories where slug = 'thunder-crackers'), 300.00, 'pcs', false, 'active', 187),
  ('SSR-188', '2k-f-188', '2K F', null, (select id from categories where slug = 'thunder-crackers'), 600.00, 'pcs', false, 'active', 188),
  ('SSR-189', '5k-f-189', '5K F', null, (select id from categories where slug = 'thunder-crackers'), 1500.00, 'pcs', false, 'active', 189),
  ('SSR-190', '10k-f-190', '10K F', null, (select id from categories where slug = 'thunder-crackers'), 3000.00, 'pcs', false, 'active', 190),
  ('SSR-191', '1-4-kg-191', '1/4 Kg', null, (select id from categories where slug = 'thunder-crackers'), 50.00, 'pcs', false, 'active', 191),
  ('SSR-192', '1-2-kg-192', '1/2 Kg', null, (select id from categories where slug = 'thunder-crackers'), 100.00, 'pcs', false, 'active', 192),
  ('SSR-193', '1-kg-193', '1 Kg', null, (select id from categories where slug = 'thunder-crackers'), 150.00, 'pcs', false, 'active', 193),
  ('SSR-194', 'cuckoo-20-item-194', 'Cuckoo - 20 Item', null, (select id from categories where slug = 'gift-box'), 320.00, 'box', false, 'active', 194),
  ('SSR-195', 'duck-25-item-195', 'Duck - 25 Item', null, (select id from categories where slug = 'gift-box'), 380.00, 'box', false, 'active', 195),
  ('SSR-196', 'dove-30-item-196', 'Dove - 30 Item', null, (select id from categories where slug = 'gift-box'), 430.00, 'box', false, 'active', 196),
  ('SSR-197', 'flamingo-35-item-197', 'Flamingo - 35 Item', null, (select id from categories where slug = 'gift-box'), 510.00, 'box', false, 'active', 197),
  ('SSR-198', 'garuda-40-item-198', 'Garuda - 40 Item', null, (select id from categories where slug = 'gift-box'), 590.00, 'box', false, 'active', 198),
  ('SSR-199', 'peacock-50-item-199', 'Peacock - 50 Item', null, (select id from categories where slug = 'gift-box'), 950.00, 'box', false, 'active', 199),
  ('SSR-200', 'diamond-60-item-200', 'Diamond - 60 Item', null, (select id from categories where slug = 'gift-box'), 1200.00, 'box', false, 'active', 200)
on conflict (sku) do update set
  slug = excluded.slug,
  name_en = excluded.name_en,
  category_id = excluded.category_id,
  mrp = excluded.mrp,
  unit = excluded.unit,
  is_discountable = excluded.is_discountable,
  status = excluded.status,
  display_order = excluded.display_order;

-- ── Sanity check: expect 200 total / 197 active ─────────────────────
do $$
declare
  v_total int;
  v_active int;
begin
  select count(*) into v_total from products where sku like 'SSR-%';
  select count(*) into v_active from products where sku like 'SSR-%' and status = 'active';
  if v_total <> 200 then
    raise exception 'Expected 200 SSR products, found %', v_total;
  end if;
  if v_active <> 197 then
    raise exception 'Expected 197 active SSR products, found %', v_active;
  end if;
  raise notice 'OK: % SSR products, % active', v_total, v_active;
end $$;

